pipeline improvements

diff --git a/.github/workflows/test-broker-upgrade-update.yml b/.github/workflows/test-broker-upgrade-update.yml
--- a/.github/workflows/test-broker-upgrade-update.yml
+++ b/.github/workflows/test-broker-upgrade-update.yml
@@ -23,32 +23,51 @@ jobs:
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Operator deployment
+      - name: Deploy Operator
         run: |
-          kubectl cluster-info
-          kubectl get pods -n kube-system
-          echo "current-context:" $(kubectl config current-context)
-          echo "environment-kubeconfig:" ${KUBECONFIG}
-          kubectl create ns pubsubplus-operator-system --save-config
-          kubectl create secret generic regcred --from-file=.dockerconfigjson=${HOME}/.docker/config.json --type=kubernetes.io/dockerconfigjson -n pubsubplus-operator-system
-          make deploy | grep created
-          kubectl rollout status deployment pubsubplus-eventbroker-operator -n pubsubplus-operator-system --timeout=30s
-          kubectl get crd | grep eventbrokers
+          for i in {1..3}; do
+            kubectl cluster-info
+            kubectl get pods -n kube-system
+            echo "current-context:" $(kubectl config current-context)
+            echo "environment-kubeconfig:" ${KUBECONFIG}
+            kubectl get ns pubsubplus-operator-system || kubectl create ns pubsubplus-operator-system
+            if kubectl get deployment pubsubplus-eventbroker-operator -n pubsubplus-operator-system; then
+              echo "pubsubplus-eventbroker-operator is already deployed"
+              break
+            else
+              kubectl apply -f <(kubectl create secret generic regcred --from-file=.dockerconfigjson=${HOME}/.docker/config.json --type=kubernetes.io/dockerconfigjson -n pubsubplus-operator-system --dry-run=client -o yaml)
+              make deploy | grep 'created \| configured'
+              kubectl rollout status deployment pubsubplus-eventbroker-operator -n pubsubplus-operator-system --timeout=240s
+              if [ $? -eq 0 ]; then
+                break
+              else
+                echo "Rollout status check failed, retrying in 20 seconds..."
+                sleep 20
+              fi
+            fi
+          done
 
       - name: Create nonHA deployment with image tag "latest"
         run: |
-          kubectl apply -f ci/manifests/eventbroker-upgrade-update.yaml | grep "test-nonha-upgrade-update"
-          sleep 5 ; kubectl get all
-          kubectl wait pods --selector app.kubernetes.io/instance=test-nonha-upgrade-update --for condition=Ready --timeout=120s | grep "condition met"
-          kubectl get po --show-labels | grep test-nonha-upgrade-update | grep "1/1"
-          kubectl get po --show-labels | grep test-nonha-upgrade-update | grep active=true
-          kubectl get sts | grep test-nonha-upgrade-update
-          kubectl get svc | grep LoadBalancer
-          kubectl port-forward svc/test-nonha-upgrade-update-pubsubplus 55555:55555 &
-          sleep 5
-          curl -O https://sftp.solace.com/download/SDKPERF_C_LINUX64
-          tar -xvf SDKPERF_C_LINUX64
-          pubSubTools/sdkperf_c -cip=tcp://localhost:55555 -mn=1000 -mr=0 -ptl=t1 -stl=t1 | grep "Total Messages"
+          for i in {1..3}; do
+            kubectl apply -f ci/manifests/eventbroker-upgrade-update.yaml | grep "test-nonha-upgrade-update"
+            sleep 5
+            if kubectl wait pods --selector app.kubernetes.io/instance=test-nonha-upgrade-update --for condition=Ready --timeout=120s | grep "condition met"; then
+              kubectl get po --show-labels | grep test-nonha-upgrade-update | grep "1/1"
+              kubectl get po --show-labels | grep test-nonha-upgrade-update | grep active=true
+              kubectl get sts | grep test-nonha-upgrade-update
+              kubectl get svc | grep LoadBalancer
+              kubectl port-forward svc/test-nonha-upgrade-update-pubsubplus 55555:55555 &
+              sleep 5
+              curl -O https://sftp.solace.com/download/SDKPERF_C_LINUX64
+              tar -xvf SDKPERF_C_LINUX64
+              pubSubTools/sdkperf_c -cip=tcp://localhost:55555 -mn=1000 -mr=0 -ptl=t1 -stl=t1 | grep "Total Messages"
+              break
+            else
+              echo "Deployment failed, retrying in 5 seconds..."
+              sleep 5
+            fi
+          done
 
       - name: Upgrade nonHA deployment to a compatible image tag - expecting automated upgrade
         run: |
diff --git a/.github/workflows/test-full-params.yml b/.github/workflows/test-full-params.yml
--- a/.github/workflows/test-full-params.yml
+++ b/.github/workflows/test-full-params.yml
@@ -23,17 +23,29 @@ jobs:
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Testing operator deployment
+      - name: Deploy Operator
         run: |
-          kubectl cluster-info
-          kubectl get pods -n kube-system
-          echo "current-context:" $(kubectl config current-context)
-          echo "environment-kubeconfig:" ${KUBECONFIG}
-          kubectl create ns pubsubplus-operator-system --save-config
-          kubectl create secret generic regcred --from-file=.dockerconfigjson=${HOME}/.docker/config.json --type=kubernetes.io/dockerconfigjson -n pubsubplus-operator-system
-          make deploy | grep created
-          kubectl rollout status deployment pubsubplus-eventbroker-operator -n pubsubplus-operator-system --timeout=30s
-          kubectl get crd | grep eventbrokers
+          for i in {1..3}; do
+            kubectl cluster-info
+            kubectl get pods -n kube-system
+            echo "current-context:" $(kubectl config current-context)
+            echo "environment-kubeconfig:" ${KUBECONFIG}
+            kubectl get ns pubsubplus-operator-system || kubectl create ns pubsubplus-operator-system
+            if kubectl get deployment pubsubplus-eventbroker-operator -n pubsubplus-operator-system; then
+              echo "pubsubplus-eventbroker-operator is already deployed"
+              break
+            else
+              kubectl apply -f <(kubectl create secret generic regcred --from-file=.dockerconfigjson=${HOME}/.docker/config.json --type=kubernetes.io/dockerconfigjson -n pubsubplus-operator-system --dry-run=client -o yaml)
+              make deploy | grep 'created \| configured'
+              kubectl rollout status deployment pubsubplus-eventbroker-operator -n pubsubplus-operator-system --timeout=240s
+              if [ $? -eq 0 ]; then
+                break
+              else
+                echo "Rollout status check failed, retrying in 20 seconds..."
+                sleep 20
+              fi
+            fi
+          done
 
       - name: Testing the Operator - nonHA
         run: |
@@ -44,10 +56,18 @@ jobs:
           kubectl create secret tls monitoring-tls --key="tls.private.pem" --cert="tls.public.pem"
           kubectl apply -f ci/manifests/eventbroker-nonha.yaml | grep "test-nonha created"
           sleep 5 ; kubectl get all
+          for i in {1..3}; do
+            kubectl wait pods --selector app.kubernetes.io/instance=test-nonha --for condition=Ready
+            if [ $? -eq 0 ]; then
+              break
+            else
+              echo "Waiting for pods failed, retrying in 5 seconds..."
+              sleep 5
+            fi
+          done
           kubectl wait --for=condition=ServiceReady eb test-nonha --timeout=120s
           kubectl wait --for=condition=NoWarnings eb test-nonha
           kubectl wait --for=condition=MonitoringReady eb test-nonha
-          kubectl wait pods --selector app.kubernetes.io/instance=test-nonha --for condition=Ready
           kubectl get po --show-labels | grep test-nonha | grep "1/1"
           kubectl get po --show-labels | grep test-nonha | grep active=true
           kubectl get sts | grep test-nonha
diff --git a/.github/workflows/test-helm-upgrade.yml b/.github/workflows/test-helm-upgrade.yml
--- a/.github/workflows/test-helm-upgrade.yml
+++ b/.github/workflows/test-helm-upgrade.yml
@@ -23,17 +23,30 @@ jobs:
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Testing operator deployment
+      - name: Deploy Operator
         run: |
-          kubectl cluster-info
-          kubectl get pods -n kube-system
-          echo "current-context:" $(kubectl config current-context)
-          echo "environment-kubeconfig:" ${KUBECONFIG}
-          kubectl create ns pubsubplus-operator-system --save-config
-          kubectl create secret generic regcred --from-file=.dockerconfigjson=${HOME}/.docker/config.json --type=kubernetes.io/dockerconfigjson -n pubsubplus-operator-system
-          make deploy | grep created
-          kubectl rollout status deployment pubsubplus-eventbroker-operator -n pubsubplus-operator-system --timeout=30s
-          kubectl get crd | grep eventbrokers
+          for i in {1..3}; do
+            kubectl cluster-info
+            kubectl get pods -n kube-system
+            echo "current-context:" $(kubectl config current-context)
+            echo "environment-kubeconfig:" ${KUBECONFIG}
+            kubectl get ns pubsubplus-operator-system || kubectl create ns pubsubplus-operator-system
+            if kubectl get deployment pubsubplus-eventbroker-operator -n pubsubplus-operator-system; then
+              echo "pubsubplus-eventbroker-operator is already deployed"
+              break
+            else
+              kubectl apply -f <(kubectl create secret generic regcred --from-file=.dockerconfigjson=${HOME}/.docker/config.json --type=kubernetes.io/dockerconfigjson -n pubsubplus-operator-system --dry-run=client -o yaml)
+              make deploy | grep 'created \| configured'
+              kubectl rollout status deployment pubsubplus-eventbroker-operator -n pubsubplus-operator-system --timeout=240s
+              if [ $? -eq 0 ]; then
+                break
+              else
+                echo "Rollout status check failed, retrying in 20 seconds..."
+                sleep 20
+              fi
+            fi
+          done
+
 
       - name: Testing the Operator - Upgrade a nonHA Helm deployment to Operator
         run: |
@@ -43,6 +56,7 @@ jobs:
           kubectl create secret tls test-tls --key="tls.key" --cert="tls.crt"
           helm repo add solacecharts https://solaceproducts.github.io/pubsubplus-kubernetes-helm-quickstart/helm-charts
           helm install my-release solacecharts/pubsubplus-dev --set solace.size=dev,solace.redundancy=false,solace.podModifierEnabled=true,tls.enabled=true,tls.serverCertificatesSecret=test-tls,solace.usernameAdminPassword=admin
+          kubectl describe pods
           echo "Waiting for broker to become active"
           until kubectl get pods --show-labels | grep pubsubplus-dev-0 | grep -m 1 -E '1/1'; do sleep 10; done
           helm test my-release | grep Phase | grep Succeeded
