pipeline improvements

diff --git a/.github/workflows/test-helm-upgrade.yml b/.github/workflows/test-helm-upgrade.yml
--- a/.github/workflows/test-helm-upgrade.yml
+++ b/.github/workflows/test-helm-upgrade.yml
@@ -6,15 +6,36 @@ jobs:
   test:
     name: Test
     runs-on: ubuntu-latest
+    # Add "id-token" with the intended permissions.
+    permissions:
+      contents: 'read'
+      id-token: 'write'
+      packages: 'read'
+
     steps:
+      - name: Set env and tools
+        run: |
+          echo "TESTNAMESPACE=op-test-helm-upgrade-$(date +%s)" >> $GITHUB_ENV
+
       - name: Check out code
         uses: actions/checkout@v4
         with:
           ref: ${{ github.head_ref }}
           fetch-depth: 0
 
-      - name: Create k8s Kind Cluster
-        uses: helm/kind-action@v1.3.0
+      - id: 'auth'
+        name: 'Authenticate to Google Cloud'
+        uses: 'google-github-actions/auth@v1.0.0'
+        with:
+          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
+          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
+          access_token_lifetime: 600s
+
+      - name: Use the GKE Autopilot test cluster
+        uses: 'google-github-actions/get-gke-credentials@v1.0.0'
+        with:
+          cluster_name: 'dev-integrationtesting'
+          location: 'us-central1'
 
       - name: Login to Github Packages
         uses: docker/login-action@v2
@@ -23,33 +44,40 @@ jobs:
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
+      - name: Setting up kubeconfig ENV for Github Chaos Action
+        run: echo ::set-env name=KUBE_CONFIG_DATA::$(base64 -w 0 ~/.kube/config)
+        env:
+          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
+
       - name: Deploy Operator
         run: |
+          echo "starting deployment"
           for i in {1..3}; do
-            kubectl cluster-info
-            kubectl get pods -n kube-system
-            echo "current-context:" $(kubectl config current-context)
-            echo "environment-kubeconfig:" ${KUBECONFIG}
-            kubectl get ns pubsubplus-operator-system || kubectl create ns pubsubplus-operator-system
-            if kubectl get deployment pubsubplus-eventbroker-operator -n pubsubplus-operator-system; then
-              echo "pubsubplus-eventbroker-operator is already deployed"
-              break
-            else
-              kubectl apply -f <(kubectl create secret generic regcred --from-file=.dockerconfigjson=${HOME}/.docker/config.json --type=kubernetes.io/dockerconfigjson -n pubsubplus-operator-system --dry-run=client -o yaml)
-              make deploy | grep 'created \| configured'
-              kubectl rollout status deployment pubsubplus-eventbroker-operator -n pubsubplus-operator-system --timeout=240s
-              if [ $? -eq 0 ]; then
-                break
-              else
-                echo "Rollout status check failed, retrying in 20 seconds..."
-                sleep 20
-              fi
-            fi
+          kubectl cluster-info
+          kubectl get pods -n kube-system
+          echo "current-context:" $(kubectl config current-context)
+          echo "environment-kubeconfig:" ${KUBECONFIG}
+          kubectl get ns pubsubplus-operator-system || kubectl create ns pubsubplus-operator-system
+          if kubectl get deployment pubsubplus-eventbroker-operator -n pubsubplus-operator-system; then
+           echo "pubsubplus-eventbroker-operator is already deployed"
+           break
+          else
+           kubectl apply -f <(kubectl create secret generic regcred --from-file=.dockerconfigjson=${HOME}/.docker/config.json --type=kubernetes.io/dockerconfigjson -n pubsubplus-operator-system --dry-run=client -o yaml)
+           make deploy | grep 'created \| configured'
+           kubectl rollout status deployment pubsubplus-eventbroker-operator -n pubsubplus-operator-system --timeout=240s
+           if [ $? -eq 0 ]; then
+             break
+           else
+             echo "Rollout status check failed, retrying in 20 seconds..."
+             sleep 20
+           fi
+          fi
           done
 
 
       - name: Testing the Operator - Upgrade a nonHA Helm deployment to Operator
         run: |
+          kubectl create ns $TESTNAMESPACE && kubectl config set-context --current --namespace=$TESTNAMESPACE
           curl -O https://sftp.solace.com/download/SDKPERF_C_LINUX64
           tar -xvf SDKPERF_C_LINUX64
           openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout tls.key -out tls.crt -subj "/CN=*"
@@ -98,3 +126,7 @@ jobs:
           sleep 1
           curl localhost:9629 | grep Exporter
           kubectl delete eventbroker test-nonha | grep deleted
+
+      - name: Delete broker deployment
+        run: |        
+          kubectl delete ns $TESTNAMESPACE --ignore-not-found
